### ISSUE TITLE
Error when trying to install through cmd (Windows Python 3.8)

### ISSUE THREAD

**Issue by AForceGaming** [beat-machine/beat-machine#70]
Microsoft Windows [Version 10.0.22631.3447]
(c) Microsoft Corporation. All rights reserved.

C:\Users\*****>pip install beatmachine
Collecting beatmachine
  Using cached beatmachine-3.2.0-py3-none-any.whl.metadata (862 bytes)
Collecting deprecation==2.*,>=2.0.0 (from beatmachine)
  Using cached deprecation-2.1.0-py2.py3-none-any.whl.metadata (4.6 kB)
Collecting jsonschema==3.*,>=3.2.0 (from beatmachine)
  Using cached jsonschema-3.2.0-py2.py3-none-any.whl.metadata (7.8 kB)
Collecting madmom (from beatmachine)
  Using cached madmom-0.16.1.tar.gz (20.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "c:\users\*****\appdata\local\programs\python\python38-32\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "c:\users\*****\appdata\local\programs\python\python38-32\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "c:\users\*****\appdata\local\programs\python\python38-32\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\*****\AppData\Local\Temp\pip-build-env-2wi1it6w\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\*****\AppData\Local\Temp\pip-build-env-2wi1it6w\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\*****\AppData\Local\Temp\pip-build-env-2wi1it6w\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\*****\AppData\Local\Temp\pip-build-env-2wi1it6w\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 12, in <module>
      ModuleNotFoundError: No module named 'Cython'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by TidisSE3** [comment]
+1

**Comment by branchpanic** [comment]
The version on PyPI hasn't been updated since the project slowed down. If you still want to run it locally, try installing directly from `main` (requires Python >= 3.12) and see if you get the same error:

```
pip install Cython
pip install git+https://github.com/beat-machine/beat-machine.git
```

This will give you the same version the site uses.
